# skill_attr = {
#     'None':None,
#     'Astrogation':['astrogation','int_','intelligence','GENERAL'],
#     'Athletics':['athletics','br','brawn','GENERAL'],
#     'Charm':['charm','pres','presence','GENERAL'],
#     'Coercion':['coercion','will','willpower','GENERAL'],
#     'Computers':['computers','int_','intelligence','GENERAL'],
#     'Cool':['cool','pres', 'presence','GENERAL'],
#     'Coordination':['coordination','agi','agility','GENERAL'],
#     'Deception':['deception','cun','cunning','GENERAL'],
#     'Discipline':['discipline','will','willpower','GENERAL'],
#     'Leadership':['leadership','pres','presence','GENERAL'],
#     'Mechanics':['mechanics','int_','intelligence','GENERAL'],
#     'Medicine':['medicine','int_','intelligence','GENERAL'],
#     'Negotiation':['negotiation','pres','presence','GENERAL'],
#     'Perception':['perception','cun','cunning','GENERAL'],
#     'Piloting Planetary':['piloting_planetary','agi','GENERAL'],
#     'Piloting Space':['piloting_space','agi','agility','GENERAL'],
#     'Resilience':['resilience','br','brawn','GENERAL'],
#     'Skullduggery':['skullduggery','cun','cunning','GENERAL'],
#     'Stealth':['stealth','agi','agility','GENERAL'],
#     'Streetwise':['streetwise','cun','cunning','GENERAL'],
#     'Survival':['survival','cun','cunning','GENERAL'],
#     'Vigilance':['vigilance','will','willpower','GENERAL'],
#     'Lightsaber':['lightsaber','br','brawn','COMBAT'],
#     'Brawl':['brawl','br','brawn','COMBAT'],
#     'Gunnery':['gunnery','agi','brawn','COMBAT'],
#     'Melee':['melee','br','brawn','COMBAT'],
#     'Ranged Light':['ranged_light','agi','agility','COMBAT'],
#     'Ranged Heavy':['ranged_heavy','agi','agility','COMBAT'],
#     'Core Worlds':['core_worlds','int_','intelligence','KNOWLEDGE'],
#     'Education':['education','int_','intelligence','KNOWLEDGE'],
#     'Lore':['lore','int_','intelligence','KNOWLEDGE'],
#     'Outer Rim':['outer_rim','int_','intelligence','KNOWLEDGE'],
#     'Underworld':['underworld','int_','intelligence','KNOWLEDGE'],
#     'Xenology':['xenology','int_','intelligence','KNOWLEDGE'],
#     'Warfare':['warfare','int_','intelligence','KNOWLEDGE']
# }